Use expect exception message,use PHPUnit namespace
opulencephp/route-matcher pull request #2
Opened 2019-01-07 15:30 UTC by peter279k

# Changed log

- Using `use PHPUnit\Framework\TestCase` for all test classes in `Test` folder because of consistency.
- Add the `expectExceptionMessage` to check whether expected exception message is same as equal exception message.

2019-01-10 02:57 UTC, davidbyoung requested changes
Thanks again!  Same thing with this PR - same comment, just in a few different spots.

2019-01-10 02:57 UTC, opulencephp commented on src/Tests/Builders/RouteBuilderTest.php
> +        $this->expectExceptionMessage('Middleware binding must either be a string or an instance of Opulence\Routing\Middleware\MiddlewareBinding');
Same comment about getting the fully-qualified class name dynamically

2019-01-10 02:57 UTC, opulencephp commented on src/Tests/Matchers/Rules/DateRuleTest.php
> +        $this->expectExceptionMessage('No formats specified for Opulence\Routing\Matchers\Rules\DateRule');
Same comment about getting the fully-qualified class name dynamically

2019-01-10 02:57 UTC, opulencephp commented on src/Tests/Matchers/Rules/RuleFactoryTest.php
> +        $this->expectExceptionMessage('Factory for rule "foo" does not return an instance of IRule');
Same comment about getting the fully-qualified class name dynamically

2019-01-12 01:04 UTC, opulencephp commented on src/Tests/Matchers/Rules/RuleFactoryTest.php
> +        $this->expectExceptionMessage('Factory for rule "foo" does not return an instance of IRule');
That's fine.  Would you mind updating the `DateRule` one, though?

Thanks!

2019-01-14 02:44 UTC, peter279k commented
@opulencephp, thank you for your reply.

I've enhanced the router expected exception message output approach.

You can take look at the latest changes via latest commit.

Thanks.

2019-01-15 18:53 UTC, merged